// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfT0HNwHZSlgeOjqMRUHQvLL2q_uFkfuw',
    appId: '1:481209266323:android:d1bd673cf73c6144f3dd66',
    messagingSenderId: '481209266323',
    projectId: 'mesclainvest123',
    storageBucket: 'mesclainvest123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXWp0EHWaYevjK1EhgE-2Qi68g0yoXXqs',
    appId: '1:481209266323:ios:cdd17946835f58c4f3dd66',
    messagingSenderId: '481209266323',
    projectId: 'mesclainvest123',
    storageBucket: 'mesclainvest123.firebasestorage.app',
    iosBundleId: 'com.example.mesclaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXWp0EHWaYevjK1EhgE-2Qi68g0yoXXqs',
    appId: '1:481209266323:ios:0e061da7713aed20f3dd66',
    messagingSenderId: '481209266323',
    projectId: 'mesclainvest123',
    storageBucket: 'mesclainvest123.firebasestorage.app',
    iosBundleId: 'q',
  );
}
